### ISSUE TITLE
Iteration 1

### ISSUE THREAD

**Issue by susiirwin** [rsbarbo/black_thursday#14]
we are working on sales analyst in Iteration 1, our goal is to have it done by july 28th morning, so we can start picking at iteration 2.

Tests are being created based on spec to support code which needs to be written

**Comment by rsbarbo** [comment]
Iteration one has been finished, we are currently passing rake (our tests) with 44 runs, 52 assertions, 0 failures, 0 errors, 0 skips, and the spec harness is currently passing with 31 examples, 0 failures
